services:
  sqldb:
    image: mysql:8.0.33
    container_name: sqldb-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: sqldb
    networks:
      - internalnet

  node-server:
    container_name: node-server-container
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/usr/code
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    environment:
      DB_HOST: sqldb
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - sqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
